# Generated by Django 2.2 on 2023-09-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0003_insborrow_ins_tudata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='file_path',
        ),
    ]
