# Generated by Django 2.2 on 2023-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab', '0004_remove_doc_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='user_risk',
            field=models.IntegerField(default=0, verbose_name='使用风险度（值越大缺少时影响越大）'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='riskfactor',
            field=models.IntegerField(default=0, verbose_name='危险性（值越大越危险）'),
        ),
    ]
